title: Victor Luccas Soares | Unity
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: "/:title"
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Victor Luccas Soares
author-img: victor-luccas-soares.jpg
about-author: Very organized and responsible person, always willing to learn more, especially when it comes to the development of graphic applications. Someone who cares for the quality, organization, readability and logic of the code he works on. Good grades at one of the best universities of my country in the CS field. Passionate about coding and aiming to become a must-have technical expert for any project.
social-github: victorluccassvl
social-linkedin: victorluccassvl
social-email: victor.luccas.svl@gmail.com

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
